<?php
$_hnews = array (
  'kid' => 'hnews',
  'pid' => 'docs',
  'title' => '动态',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'cfgs' => 'parts=1',
  'f' => 
  array (
    'lpid' => 
    array (
      'kid' => 'lpid',
      'title' => '关联楼盘',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => 'house.1',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'pick',
      'fmexstr' => '',
      'cfgs' => '',
    ),
    'exid' => 
    array (
      'kid' => 'exid',
      'title' => '平台码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '0',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '48',
      'fmsize' => '240',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
    'title' => 
    array (
      'kid' => 'title',
      'title' => '标题',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'tit:2-60',
      'vtip' => '标题2-60字符',
      'vmax' => '60',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
    'color' => 
    array (
      'kid' => 'color',
      'title' => '标题颜色',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'nul:str:4-7',
      'vtip' => '如:#FF00FF',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'color',
      'fmexstr' => 'title',
      'cfgs' => '',
    ),
    'ndb_repeat' => 
    array (
      'kid' => 'ndb_repeat',
      'title' => '检查重复',
      'etab' => '0',
      'type' => 'repeat',
      'dbtype' => 'nodb',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'repeat',
      'fmexstr' => '',
      'cfgs' => 'news,title',
    ),
    'remark' => 
    array (
      'kid' => 'remark',
      'title' => '内容',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '420x8',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
  ),
  'i' => 
  array (
    'h1012' => 
    array (
      'kid' => 'h1012',
      'pid' => '0',
      'title' => '开盘',
      'deep' => '1',
      'frame' => '0',
      'char' => 'K',
      'cfgs' => '',
    ),
    'h1016' => 
    array (
      'kid' => 'h1016',
      'pid' => '0',
      'title' => '交房',
      'deep' => '1',
      'frame' => '0',
      'char' => 'J',
      'cfgs' => '',
    ),
    'h1018' => 
    array (
      'kid' => 'h1018',
      'pid' => '0',
      'title' => '资讯',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Z',
      'cfgs' => '',
    ),
    'h1020' => 
    array (
      'kid' => 'h1020',
      'pid' => '0',
      'title' => '预售',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
  ),
);
?>