<?php
$_prsafe = array (
  'kid' => 'prsafe',
  'pid' => 'score',
  'title' => '安全参数',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'f' => 
  array (
    'safe_site' => 
    array (
      'kid' => 'safe_site',
      'title' => '全站唯一随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][site]',
      'val' => 'name-EJttq-g4tic-AfFG7-CTOCW-0Y0za',
    ),
    'safe_pass' => 
    array (
      'kid' => 'safe_pass',
      'title' => '密码加密-混淆码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18-48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][pass]',
      'val' => 'pass-FEFsl-oBU+9-d7-Mq-6gP0c-rycre',
    ),
    'safe_adminer' => 
    array (
      'kid' => 'safe_adminer',
      'title' => 'm混淆码-adminer',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18-48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][adminer]',
      'val' => 'adm-MPaI.-yA-Uk-xuYbX-Vcf0H--9W_H',
    ),
    'safe_api' => 
    array (
      'kid' => 'safe_api',
      'title' => 'API-随即码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][api]',
      'val' => 'api-SpQa9-EADIG-KpUqz-yDkmx-dxL9o',
    ),
    'safe_js' => 
    array (
      'kid' => 'safe_js',
      'title' => 'JS-随即码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][js]',
      'val' => 'js-IhB5X-tw4Ff-rcrzA-Q4odx-ns4vC',
    ),
    'safe_other' => 
    array (
      'kid' => 'safe_other',
      'title' => 'Other-其他随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][other]',
      'val' => 'other-wDiuD-2ohu4-CAmuq-jyQlT-2dGWy',
    ),
    'safe_safil' => 
    array (
      'kid' => 'safe_safil',
      'title' => '安全过滤-随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][safil]',
      'val' => 'safil-esgzC-PPoMr-ASWCs-bk2da-13F7r',
    ),
    'safe_safix' => 
    array (
      'kid' => 'safe_safix',
      'title' => '安全过滤-数组前缀',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:4-4',
      'vtip' => '4位',
      'vmax' => '4',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][safix]',
      'val' => '_757',
    ),
    'safe_rnum' => 
    array (
      'kid' => 'safe_rnum',
      'title' => '数字-随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rnum]',
      'val' => '544089822451401069332952',
    ),
    'safe_rspe' => 
    array (
      'kid' => 'safe_rspe',
      'title' => '特殊字符-随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rspe]',
      'val' => 'pzb-P_)WPOW9-@D0+89D9-hUvDhxbD',
    ),
    'safe_rndch6' => 
    array (
      'kid' => 'safe_rndch6',
      'title' => '随机6位码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '6',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '6',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rndch6]',
      'val' => 'eQ6.yS',
    ),
    'safe_rndtab' => 
    array (
      'kid' => 'safe_rndtab',
      'title' => '随机62位不重复码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '62',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '62',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rndtab]',
      'val' => 'EybKYjwNJnh81oXZ6tW7GcAq0UOCuvlSkRFDTH2LIg3rB9sVmzeQMpda4Pf5xi',
    ),
    'tout_admin' => 
    array (
      'kid' => 'tout_admin',
      'title' => '管理后台_超时时间',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '255',
      'dbdef' => '1',
      'vreg' => 'n+d',
      'vtip' => '单位(时),建议1~4之间',
      'vmax' => '4',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => 'tout_admin',
      'val' => '1',
    ),
    'tout_member' => 
    array (
      'kid' => 'tout_member',
      'title' => '会员_超时时间',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '255',
      'dbdef' => '4',
      'vreg' => 'n+d',
      'vtip' => '单位(时),建议1~4之间',
      'vmax' => '4',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => 'tout_member',
      'val' => '4',
    ),
  ),
);
?>